import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

import { Jura } from "next/font/google";
import localFont from "next/font/local";
import Image from "next/image";
import Blob1 from "@/public/blobs/blob-1.svg";
import Blob2 from "@/public/blobs/blob-2.svg";

import "./globals.css";
import Footer from "@/components/footer";
import WalletProvider from "@/components/wallet-provider";

const jura = Jura({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const furore = localFont({
  src: "./fonts/furore.otf",
  variable: "--font-furore",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jura.className} ${furore?.variable} bg-black`}>
        <Image
          src={Blob1}
          height={450}
          alt="services-blob"
          className="absolute left-0 top-0 -z-10"
        />

        <Image
          src={Blob2}
          height={350}
          alt="services-blob"
          className="absolute right-0 top-0 -z-10"
        />

        <ToastContainer />

        <WalletProvider>{children}</WalletProvider>

        <Footer />
      </body>
    </html>
  );
}
