import type { Metadata } from "next";
import { Jura } from "next/font/google";
import localFont from "next/font/local";

import "./globals.css";
import Footer from "@/components/footer";

const jura = Jura({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const furore = localFont({
  src: "./fonts/furore.otf",
  variable: "--font-furore",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jura.className} ${furore?.variable}`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
